SELECT * FROM QNA_BOARD;
SELECT * FROM BOOKMARK;
SELECT * FROM CART_DETAIL;
SELECT * FROM CART;
SELECT * FROM LIKE_RKH;
SELECT * FROM MEALKIT_BOARD;
SELECT * FROM MEALKIT_COMMENT;
SELECT * FROM MEALKIT_STAR_SCORE;
SELECT * FROM MEMBER;
SELECT * FROM PAYMENT;
SELECT * FROM RECIPE_BOARD;
SELECT * FROM RECIPE_CATEGORY;
SELECT * FROM RECIPE_COMMENT;
SELECT * FROM REPORT;

COMMIT

INSERT INTO QNA_BOARD VALUES();
INSERT INTO BOOKMARK VALUES();
INSERT INTO CART_DETAIL VALUES();
INSERT INTO CART VALUES();
INSERT INTO LIKE_RKH VALUES();
INSERT INTO MEALKIT_BOARD VALUES();
INSERT INTO MEALKIT_COMMENT VALUES();
INSERT INTO MEALKIT_STAR_SCORE VALUES();
INSERT INTO MEMBER VALUES();
INSERT INTO PAYMENT VALUES();
INSERT INTO RECIPE_BOARD VALUES();
INSERT INTO RECIPE_CATEGORY VALUES();
INSERT INTO RECIPE_COMMENT VALUES();
INSERT INTO REPORT VALUES();